[captureMappings._.highlights]
"@variable"                    = "@variable" #  various variable names
"@variable.builtin"            = "@variable.defaultLibrary" #  built-in variable names (e.g. `this`, `self`)
"@variable.parameter"          = "@parameter" #  parameters of a function
"@variable.parameter.builtin"  = "@parameter.defaultLibrary" #  special parameters (e.g. `_`, `it`)
"@variable.member"             = "@property" #  object and struct fields
"@constant"             = "@variable.readonly" # constant identifiers
"@constant.builtin"     = "@variable.readonly.defaultLibrary" # built-in constant values
"@constant.macro"       = "@macro" # constants defined by the preprocessor
"@module"               = "@namespace" # modules or namespaces
"@module.builtin"       = "@namespace.defaultLibrary" # built-in modules or namespaces
"@label"                = "@variable" # `GOTO` and other labels (e.g. `label:` in C), including heredoc labels
"@string"               = "@string" # string literals
"@string.documentation" = "@string.documentation" # string documenting code (e.g. Python docstrings)
"@string.regexp"        = "@regexp" # regular expressions
"@string.escape"        = "@string" # escape sequences
"@string.special"       = "@string" # other special strings (e.g. dates)
"@string.special.symbol"= "@string" # symbols or atoms
"@string.special.path"  = "@string" # filenames
"@string.special.url"   = "@string" # URIs (e.g. hyperlinks)
"@character"            = "@string" # character literals
"@character.special"    = "@string" # special characters (e.g. wildcards)
"@boolean"              = "@keyword" # boolean literals
"@number"               = "@number" # numeric literals
"@number.float"         = "@number" # floating-point number literals
"@type"                 = "@type" # type or class definitions and annotations
"@type.builtin"         = "@type.defaultLibrary" # built-in types
"@type.definition"      = "@type.definition" # identifiers in type definitions (e.g. `typedef <type> <identifier>` in C)
"@attribute"            = "@decorator" # attribute annotations (e.g. Python decorators, Rust lifetimes)
"@attribute.builtin"    = "@decorator.defaultLibrary" # builtin annotations (e.g. `@property` in Python)
"@property"             = "@property" # the key in key/value pairs
"@function"             = "@function" # function definitions
"@function.builtin"     = "@function.defaultLibrary" # built-in functions
"@function.call"        = "@function" # function calls
"@function.macro"       = "@macro" # preprocessor macros
"@function.method"      = "@method" # method definitions
"@function.method.call" = "@method" # method calls
"@constructor"          = "@function" # constructor calls and definitions
"@operator"             = "@operator" # symbolic operators (e.g. `+`, `*`)
"@keyword"              = "@keyword" # keywords not fitting into specific categories
"@keyword.coroutine"    = "@keyword.async" # keywords related to coroutines (e.g. `go` in Go, `async/await` in Python)
"@keyword.function"     = "@keyword" # keywords that define a function (e.g. `func` in Go, `def` in Python)
"@keyword.operator"     = "@operator" # operators that are English words (e.g. `and`, `or`)
"@keyword.import"       = "@keyword" # keywords for including or exporting modules (e.g. `import`, `from` in Python)
"@keyword.type"         = "@keyword" # keywords describing namespaces and composite types (e.g. `struct`, `enum`)
"@keyword.modifier"     = "@modifier" # keywords modifying other constructs (e.g. `const`, `static`, `public`)
"@keyword.repeat"       = "@keyword" # keywords related to loops (e.g. `for`, `while`)
"@keyword.return"       = "@keyword" # keywords like `return` and `yield`
"@keyword.debug"        = "@keyword" # keywords related to debugging
"@keyword.exception"    = "@keyword" # keywords related to exceptions (e.g. `throw`, `catch`)
"@keyword.conditional"  = "@keyword" #      keywords related to conditionals (e.g. `if`, `else`)
"@keyword.conditional.ternary" = "@operator" # ternary operator (e.g. `?`, `:`)
"@keyword.directive"         = "@macro" #  various preprocessor directives and shebangs
"@keyword.directive.define"   = "@macro" # preprocessor definition directives
"@punctuation.delimiter" = "" # delimiters (e.g. `;`, `.`, `,`)
"@punctuation.bracket"   = "" # brackets (e.g. `()`, `{}`, `[]`)
"@punctuation.special"   = "" # special symbols (e.g. `{}` in string interpolation)
"@comment"               = "@comment" # line and block comments
"@comment.documentation" = "@comment.documentation" # comments documenting code
"@comment.error"         = "@comment" # error-type comments (e.g. `ERROR`, `FIXME`, `DEPRECATED`)
"@comment.warning"       = "@comment" # warning-type comments (e.g. `WARNING`, `FIX`, `HACK`)
"@comment.todo"          = "@comment" # todo-type comments (e.g. `TODO`, `WIP`)
"@comment.note"          = "@comment" # note-type comments (e.g. `NOTE`, `INFO`, `XXX`)
"@markup.strong"         = "" # bold text
"@markup.italic"         = "" # italic text
"@markup.strikethrough"  = "" # struck-through text
"@markup.underline"      = "" # underlined text (only for literal underline markup!)
"@markup.heading"        = "" # headings, titles (including markers)
"@markup.heading.1"      = "" # top-level heading
"@markup.heading.2"      = "" # section heading
"@markup.heading.3"      = "" # subsection heading
"@markup.heading.4"      = "" # and so on
"@markup.heading.5"      = "" # and so forth
"@markup.heading.6"      = "" # six levels ought to be enough for anybody
"@markup.quote"          = "" # block quotes
"@markup.math"           = "" # math environments (e.g. `$ ... $` in LaTeX)
"@markup.link"           = "" # text references, footnotes, citations, etc.
"@markup.link.label"     = "" # link, reference descriptions
"@markup.link.url"       = "" # URL-style links
"@markup.raw"            = "@string" # literal or verbatim text (e.g. inline code)
"@markup.raw.block"      = "@string" # literal or verbatim text as a stand-alone block
"@markup.list"           = "" # list markers
"@markup.list.checked"   = "" # checked todo-style list markers
"@markup.list.unchecked" = "" # unchecked todo-style list markers
"@diff.plus"             = "" # added text (for diff files)
"@diff.minus"            = "" # deleted text (for diff files)
"@diff.delta"            = "" # changed text (for diff files)
"@tag"                   = "@class" # XML-style tag names (e.g. in XML, HTML, etc.)
"@tag.builtin"           = "@class.defaultLibrary" # builtin tag names (e.g. HTML5 tags)
"@tag.attribute"         = "@property" # XML-style tag attributes
"@tag.delimiter"         = "" # XML-style tag delimiters
